package com.openmeteo.api.historical.params

enum class Hourly {
    temperature_2m,
    relativehumidity_2m,
    dewpoint_2m,
    apparent_temperature,
    pressure_msl,
    surface_pressure,
    precipitation,
    rain,
    snowfall,
    cloudcover,
    cloudcover_low,
    cloudcover_mid,
    cloudcover_high,
    shortwave_radiation,
    direct_radiation,
    direct_normal_irradiance,
    diffuse_radiation,
    windspeed_10m,
    windspeed_100m,
    winddirection_10m,
    winddirection_100m,
    windgusts_10m,
    et0_fao_evapotranspiration,
    vapor_pressure_deficit,
    soil_temperature_0_to_7cm,
    soil_temperature_7_to_28cm,
    soil_temperature_28_to_100cm,
    soil_temperature_100_to_255cm,
    soil_moisture_0_to_7cm,
    soil_moisture_7_to_28cm,
    soil_moisture_28_to_100cm,
    soil_moisture_100_to_255cm,
}
