// automatically generated by the FlatBuffers compiler, do not modify

package com.openmeteo.sdk

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class Aggregation (val value: UByte) {
    companion object {
        val None = Aggregation(0u)
        val Minimum = Aggregation(1u)
        val Maximum = Aggregation(2u)
        val Mean = Aggregation(3u)
        val P10 = Aggregation(4u)
        val P25 = Aggregation(5u)
        val Median = Aggregation(6u)
        val P75 = Aggregation(7u)
        val P90 = Aggregation(8u)
        val Dominant = Aggregation(9u)
        val Sum = Aggregation(10u)
        val Spread = Aggregation(11u)
        val names : Array<String> = arrayOf("none", "minimum", "maximum", "mean", "p10", "p25", "median", "p75", "p90", "dominant", "sum", "spread")
        fun name(e: Aggregation) : String = names[e.value.toInt()]
    }
}

typealias AggregationArray = UByteArray
