// automatically generated by the FlatBuffers compiler, do not modify

package com.openmeteo.sdk

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class Unit (val value: UByte) {
    companion object {
        val Undefined = Unit(0u)
        val Celsius = Unit(1u)
        val Centimetre = Unit(2u)
        val CubicMetrePerCubicMetre = Unit(3u)
        val CubicMetrePerSecond = Unit(4u)
        val DegreeDirection = Unit(5u)
        val DimensionlessInteger = Unit(6u)
        val Dimensionless = Unit(7u)
        val EuropeanAirQualityIndex = Unit(8u)
        val Fahrenheit = Unit(9u)
        val Feet = Unit(10u)
        val Fraction = Unit(11u)
        val GddCelsius = Unit(12u)
        val GeopotentialMetre = Unit(13u)
        val GrainsPerCubicMetre = Unit(14u)
        val GramPerKilogram = Unit(15u)
        val Hectopascal = Unit(16u)
        val Hours = Unit(17u)
        val Inch = Unit(18u)
        val Iso8601 = Unit(19u)
        val JoulePerKilogram = Unit(20u)
        val Kelvin = Unit(21u)
        val Kilopascal = Unit(22u)
        val KilogramPerSquareMetre = Unit(23u)
        val KilometresPerHour = Unit(24u)
        val Knots = Unit(25u)
        val MegajoulePerSquareMetre = Unit(26u)
        val MetrePerSecondNotUnitConverted = Unit(27u)
        val MetrePerSecond = Unit(28u)
        val Metre = Unit(29u)
        val MicrogramsPerCubicMetre = Unit(30u)
        val MilesPerHour = Unit(31u)
        val Millimetre = Unit(32u)
        val Pascal = Unit(33u)
        val PerSecond = Unit(34u)
        val Percentage = Unit(35u)
        val Seconds = Unit(36u)
        val UnixTime = Unit(37u)
        val UsAirQualityIndex = Unit(38u)
        val WattPerSquareMetre = Unit(39u)
        val WmoCode = Unit(40u)
        val names : Array<String> = arrayOf("undefined", "celsius", "centimetre", "cubic_metre_per_cubic_metre", "cubic_metre_per_second", "degree_direction", "dimensionless_integer", "dimensionless", "european_air_quality_index", "fahrenheit", "feet", "fraction", "gdd_celsius", "geopotential_metre", "grains_per_cubic_metre", "gram_per_kilogram", "hectopascal", "hours", "inch", "iso8601", "joule_per_kilogram", "kelvin", "kilopascal", "kilogram_per_square_metre", "kilometres_per_hour", "knots", "megajoule_per_square_metre", "metre_per_second_not_unit_converted", "metre_per_second", "metre", "micrograms_per_cubic_metre", "miles_per_hour", "millimetre", "pascal", "per_second", "percentage", "seconds", "unix_time", "us_air_quality_index", "watt_per_square_metre", "wmo_code")
        fun name(e: Unit) : String = names[e.value.toInt()]
    }
}

typealias UnitArray = UByteArray
